### ISSUE TITLE
Typescript problems in recent versions in older GraphQL js versions

### ISSUE THREAD

**Issue by tobiasdiez** [Urigo/graphql-scalars#1195]
**Describe the bug**

There doesn't seem to be any typescript information in the recent versions.
In fact, after an `import { DateTimeResolver, EmailAddressResolver } from 'graphql-scalars'` both objects have the type `any`.

**To Reproduce**
Steps to reproduce the behavior: Upgrade from 1.12.0 to 1.13.1

https://github.com/JabRef/JabRefOnline/pull/604

**Expected behavior**

Provide typescript info 

**Environment:**

- OS: Ubuntu
- GraphQL Scalars Version: 1.13.1
- NodeJS: 

**Additional context**

**Comment by jcpage** [comment]
Can confirm, when I updated from 1.12.0 to 1.13.1 I get about 100 errors similar to this:

node_modules/graphql-scalars/index.d.ts:9:11 - error TS2315: Type 'GraphQLScalarType' is not generic.
9     Date: import("graphql").GraphQLScalarType<Date, string>;

**Comment by ardatan** [comment]
Hmm we are using GraphQL js v16 for TS build. I think you are using the older version of GraphQL js that doesn't have generics in GraphQLScalarType.
Actually we don't explicitly use generics in GrphQLScalarType calls but the configuration object GraphQLScalarTypeConfig which has generics since v14. During TS Build, I think scalar types get inferred GraphQLScalarTypeConfig.
Adding type annotations without generics for every single GraphQLScalarType might fix this backwards compatibility issue.

**Comment by jcpage** [comment]
Hmm, I am using a pretty recent version of graphql js, 15.7.2.   16 was released less than 3 weeks ago so I'm sure many people still want to stick with 15.X for a while.

**Comment by ardatan** [comment]
I didn't say we should avoid it. I just explained the source of the problem.

**Comment by ardatan** [comment]
1.13.2 should be ok with <v16

**Comment by tobiasdiez** [comment]
It is indeed fixed now, thanks!

**Comment by jcpage** [comment]
Hmm, I am still getting "Type 'GraphQLScalarType' is not generic" errors - though I am only getting about half as many as before.  It looks like any errors in ./scalars/<TYPE>.d.ts went away, so only the ones in ./index..d.ts remain.   I'm attaching the diff of the old vs new errors.  Let me know if there is anything else I can provide that might be helpful.

[errors.txt](https://github.com/Urigo/graphql-scalars/files/7541327/errors.txt)

**Comment by ardatan** [comment]
Could you create a reproduction on CodeSandbox? Thanks

**Comment by jcpage** [comment]
Ok, this repro's it: https://codesandbox.io/s/scalars-example-9svtj

Can just run "yarn build" in a prompt to see it.

Simplifying it down to the minimum made me realize it's related to using graphql nexus's "asNexusMethod" on a type from graphql-scalars.

**Comment by ardatan** [comment]
I think it is good with the latest version now;
https://codesandbox.io/s/scalars-example-forked-8bcr3?file=/package.json

**Comment by jcpage** [comment]
Can confirm that fixed my issue, thanks!
